### ISSUE TITLE
Rust client feature and QA tasks

### ISSUE THREAD

**Issue by cbrzn** [polywrap/rust-client#21]
### Core Features
- [x] Add support for WRAP manifest (https://github.com/polywrap/rust-client/pull/18)
- [x] Add support for interfaces (https://github.com/polywrap/rust-client/commit/2a163a6a3d1d566fde5ded9277fcf34c66e25409)
- [x] Add support for env (https://github.com/polywrap/rust-client/pull/15)
- [x] Create client config builder package (https://github.com/polywrap/rust-client/issues/22)
- [x] Add support for plugins (https://github.com/polywrap/rust-client/pull/12)
- [x] Implement URI resolution (https://github.com/polywrap/rust-client/issues/23)
- [x] Add support for plugin codegen  (https://github.com/polywrap/toolchain/pull/1428)
- [ ] Add support for app codegen

### Testing
- [x]  #37 
- [ ] Exhaustive tests `resolvers` package
- [ ] Exhaustive tests `manifest` package
- [ ] Exhaustive tests `plugin` package
- [ ] Exhaustive tests `wasm` package
- [ ] Exhaustive tests `builder` package
- [ ] Exhaustive tests `msgpack` package

### QA & Refactors
- [x] Support env in plugins (https://github.com/polywrap/rust-client/issues/20)
- [x] Dynamic minimum memory of WASM module in instantiation (https://github.com/polywrap/rust-client/issues/17)
- [x] Add default config builder (once #23 is closed)
